[build]
  command = "cd back-end && npm install && npm run build && cd .. && cd front-end/ && npm install && npm run build"
  functions = "back-end/functions/"
  publish = "front-end/build/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200